<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RccMigration\RccMigration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.26300" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7cdd5954-a6ad-4688-bd83-65d51bef09f7</UserSecretsId>
  </PropertyGroup>

</Project>
